# Generated by Django 2.2.1 on 2019-06-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfileImage'),
        ),
    ]
