# Generated by Django 2.2.1 on 2019-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190605_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='users/default.png', upload_to='users/'),
        ),
        migrations.DeleteModel(
            name='UserProfileImage',
        ),
    ]
