# Generated by Django 2.2.1 on 2019-06-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodstonotificateabout',
            name='good',
        ),
        migrations.AddField(
            model_name='goodstonotificateabout',
            name='interested_good',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
