# Generated by Django 2.2.1 on 2019-06-08 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_personal', '0002_auto_20190607_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstonotificateabout',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
