# Generated by Django 2.2.1 on 2019-06-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_personal', '0003_auto_20190609_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='paltform',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Paltform',
        ),
    ]
