# Generated by Django 2.2.1 on 2019-06-09 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_personal', '0004_auto_20190610_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstonotificateabout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
